CREATE DATABASE IF NOT EXISTS lab_10;

USE lab_10;

CREATE TABLE IF NOT EXISTS Products (
    ID int(11) NOT NULL AUTO_INCREMENT,
    ProductType VARCHAR (60) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Price DECIMAL(7,2) NOT NULL,
    Description Text,
    Shipper VARCHAR(255) DEFAULT NULL,
    Weight DECIMAL(5,2) DEFAULT NULL,
    IsRecyclable TINYINT(1) DEFAULT NULL,
    PRIMARY KEY (ID)
);